Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AndrewApp.Contexts;
using AndrewApp.Models;

namespace AndrewApp.Controllers
{
    public class ClassesController : Controller
    {
        private readonly MainContext _context;

        public ClassesController(MainContext context)
        {
            _context = context;
        }

        // GET: Classes
        public async Task<IActionResult> Index()
        {
            var mainContext = _context.Classes.Include(@class => @class.Department).Include(@class => @class.Lecturer);
            return View(await mainContext.ToListAsync());
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes
                .Include(@class => @class.Department)
                .Include(@class => @class.Lecturer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LecturerId"] = new SelectList(_context.Lecturers, "Id", "FullName");
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DepartmentId,LecturerId,Name")] Class @class)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@class);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", @class.DepartmentId);
            ViewData["LecturerId"] = new SelectList(_context.Lecturers, "Id", "FullName", @class.LecturerId);
            return View(@class);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes.FindAsync(id);
            if (@class == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", @class.DepartmentId);
            ViewData["LecturerId"] = new SelectList(_context.Lecturers, "Id", "FullName", @class.LecturerId);
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DepartmentId,LecturerId,Name")] Class @class)
        {
            if (id != @class.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", @class.DepartmentId);
            ViewData["LecturerId"] = new SelectList(_context.Lecturers, "Id", "FullName", @class.LecturerId);
            return View(@class);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes
                .Include(@class => @class.Department)
                .Include(@class => @class.Lecturer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @class = await _context.Classes.FindAsync(id);
            _context.Classes.Remove(@class);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassExists(int id)
        {
            return _context.Classes.Any(e => e.Id == id);
        }
    }
}

Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AndrewApp.Contexts;
using AndrewApp.Models;

namespace AndrewApp.Controllers
{
    public class GradesController : Controller
    {
        private readonly MainContext _context;

        public GradesController(MainContext context)
        {
            _context = context;
        }

        // GET: Grades
        public async Task<IActionResult> Index()
        {
            var mainContext = _context.Grades.Include(g => g.Class).Include(g => g.Project).Include(g => g.Student);
            return View(await mainContext.ToListAsync());
        }

        // GET: Grades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades
                .Include(g => g.Class)
                .Include(g => g.Project)
                .Include(g => g.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // GET: Grades/Create
        public IActionResult Create()
        {
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Name");
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Subject");
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FullName");
            return View();
        }

        // POST: Grades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentId,ProjectId,ClassId,Value,GivenAt")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grade);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Name", grade.ClassId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Subject", grade.ProjectId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FullName", grade.StudentId);
            return View(grade);
        }

        // GET: Grades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades.FindAsync(id);
            if (grade == null)
            {
                return NotFound();
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Name", grade.ClassId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Subject", grade.ProjectId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FullName", grade.StudentId);
            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentId,ProjectId,ClassId,Value,GivenAt")] Grade grade)
        {
            if (id != grade.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GradeExists(grade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Name", grade.ClassId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Subject", grade.ProjectId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FullName", grade.StudentId);
            return View(grade);
        }

        // GET: Grades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades
                .Include(g => g.Class)
                .Include(g => g.Project)
                .Include(g => g.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grade = await _context.Grades.FindAsync(id);
            _context.Grades.Remove(grade);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GradeExists(int id)
        {
            return _context.Grades.Any(e => e.Id == id);
        }
    }
}

Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AndrewApp.Contexts;
using AndrewApp.Models;

namespace AndrewApp.Controllers
{
    public class GroupsController : Controller
    {
        private readonly MainContext _context;

        public GroupsController(MainContext context)
        {
            _context = context;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            var mainContext = _context.Groups.Include(@group => @group.Department).Include(@group => @group.Specialisation);
            return View(await mainContext.ToListAsync());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .Include(@group => @group.Department)
                .Include(@group => @group.Specialisation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["SpecialisationId"] = new SelectList(_context.Specialisations, "Id", "Name");
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SpecialisationId,DepartmentId,Name")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", @group.DepartmentId);
            ViewData["SpecialisationId"] = new SelectList(_context.Specialisations, "Id", "Name", @group.SpecialisationId);
            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", @group.DepartmentId);
            ViewData["SpecialisationId"] = new SelectList(_context.Specialisations, "Id", "Name", @group.SpecialisationId);
            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SpecialisationId,DepartmentId,Name")] Group @group)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", @group.DepartmentId);
            ViewData["SpecialisationId"] = new SelectList(_context.Specialisations, "Id", "Name", @group.SpecialisationId);
            return View(@group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .Include(@group => @group.Department)
                .Include(@group => @group.Specialisation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Groups.FindAsync(id);
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e-Indeks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .fonta-white {
            color: #f8f9fa !important;
        }

            .fonta-white:hover {
                color: #80bdff !important;
            }
    </style>

    <!--STYLE DO LOYAUT MENU DAC-->
    <style>
        input[type='file'] {
            color: rgba(0, 0, 0, 0) !important;
        }

        .xcustom-file-input::-webkit-file-upload-button {
            visibility: hidden;
        }

        .xcustom-file-input::before {
            content: 'Wybierz plik' !important;
            display: inline-block !important;
            background-color: #1b6ec2 !important;
            border: 1px solid #1861ac !important;
            border-radius: 0.25rem !important;
            padding: 0.375rem 0.75rem !important;
            outline: none !important;
            font-weight: 400 !important;
            font-size: 1rem !important;
            color: white !important;
        }

        .xcustom-file-input:hover::before {
            border-color: black !important;
        }

        .xcustom-file-input:active::before {
            background: -webkit-linear-gradient(top, #e3e3e3, #f9f9f9) !important;
        }
    </style>

    <style>
        .formx-control {
            display: block;
            //width: 100%;
            height: calc(1.5em + 0.75rem + 2px);
            padding: 0.375rem 0.75rem;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

            .formx-control:focus {
                color: #495057;
                background-color: #fff;
                border-color: #80bdff;
                outline: 0;
                box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
            }




            .formx-control::-webkit-input-placeholder {
                color: #6c757d;
                opacity: 1;
            }



            .formx-control::-moz-placeholder {
                color: #6c757d;
                opacity: 1;
            }



            .formx-control:-ms-input-placeholder {
                color: #6c757d;
                opacity: 1;
            }



            .formx-control::-ms-input-placeholder {
                color: #6c757d;
                opacity: 1;
            }



            .formx-control::placeholder {
                color: #6c757d;
                opacity: 1;
            }



            .formx-control:disabled, .form-control[readonly] {
                background-color: #e9ecef;
                opacity: 1;
            }



        select.formx-control:focus::-ms-value {
            color: #495057;
            background-color: #fff;
        }

        .formx-control::-ms-expand {
            background-color: transparent;
            border: 0;
        }
    </style>
</head>
<body>
    <header>
        <nav style="        background-color: #343a40 !important;" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a style=" color: #f8f9fa!important;" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">e-Indeks</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="hdmenu" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Departments" asp-action="Index">Wydziały</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Lecturers" asp-action="Index">Wykładowcy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Classes" asp-action="Index">Przedmioty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Groups" asp-action="Index">Grupy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Projects" asp-action="Index">Projekty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Specialisations" asp-action="Index">Specializacje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Students" asp-action="Index">Studenci</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fonta-white" asp-area="" asp-controller="Grades" asp-action="Index">Oceny</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - e-Indeks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <!--SCRIPT na UPLOAD PHOTO FILE-->
    <script>

        const url = window.location.href;

        const lastSegment = url.split("/").pop();

        console.log(lastSegment); // "playlist"


        var imagesObject = [];

        function handleFileSelect(evt) {
            var files = evt.target.files; // FileList object

            // Loop through the FileList and render image files as thumbnails.
            for (var i = 0, f; f = files[i]; i++) {

                // Only process image files.
                if (!f.type.match('image.*')) {
                    continue;
                }

                var reader = new FileReader();

                // Closure to capture the file information.
                reader.onload = function (e) {
                    displayImgData(e.target.result)
                    addImage(e.target.result);
                };

                reader.readAsDataURL(f);
            }
        }

        function loadFromLocalStorage() {
            var images = JSON.parse(localStorage.getItem(lastSegment))

            if (images && images.length > 0) {
                imagesObject = images;

                displayNumberOfImgs();
                images.forEach(displayImgData);
            }
        }

        function addImage(imgData) {
            imagesObject.push(imgData);
            displayNumberOfImgs();
            localStorage.setItem(lastSegment, JSON.stringify(imagesObject));
        }

        function displayImgData(imgData) {
            var span = document.createElement('span');
            document.getElementById("imageid").src = imgData;
            //span.innerHTML = '<img class="thumb" src="' + imgData + '"/>';
            //document.getElementById('list').insertBefore(span, null);
        }

        function displayNumberOfImgs() {
            if (imagesObject.length > 0) {

                document.getElementById("state").innerHTML = "Zdjęcie wgrane";//imagesObject.length + " " + ((imagesObject.length > 1) ? "s" : "") + " stored in your browser";

                document.getElementById("deleteImgs").style.display = "inline";

            } else {
                document.getElementById("state").innerHTML = "Brak zdjęcia";
                document.getElementById("deleteImgs").style.display = "none";
            }


        }

        function deleteImages() {
            imagesObject = [];
            localStorage.removeItem(lastSegment);
            displayNumberOfImgs()
            //document.getElementById('list').innerHTML = "";
            document.getElementById("imageid").src = "https://devsi.pl/images/empty-avatar.jpg";
        }

        document.getElementById('files').addEventListener('change', handleFileSelect, false);
        document.getElementById('deleteImgs').addEventListener("click", deleteImages);
        loadFromLocalStorage();
    </script>

</body>
</html>